### ISSUE TITLE
Rename DockerHub organization

### ISSUE THREAD

**Issue by nebhale** [paketo-buildpacks/stacks#22]
For consistency with the GCR repository name, the DockerHub coordinates for our image mirrors should be `paketo-buildpacks` rather than `paketobuildpacks`.

**Comment by martyspiewak** [comment]
It is my understanding that DockerHub does not allow hyphens in the organization name, which is why we were forced to choose `paketobuildpacks`. I just attempted again to create a name with a hyphen and it did not allow it. If you have seen organizations with hyphens please let me know and we can can investigate how we might be able to do this.

**Comment by nebhale** [comment]
Yep, you're right.  I was thrown because it didn't do real-time validation.
