### ISSUE TITLE
Investigate retrieving CPE metadata for stack dependencies

### ISSUE THREAD

**Issue by sophiewigmore** [paketo-buildpacks/stacks#71]
Currently, our stack metadata does not include any information about the CPEs (Common Platform Enumeration) associated with each stack dependency.
We should investigate if we can retrieve this information for each dependency as a part of the work outlined in [the BOM RFC](https://github.com/sophiewigmore/rfcs/blob/7f03362451a40fc3d2e5cb3d8de862b745c74180/text/0028-bill-of-materials.md).
If this is possible, we should file issues to add CPE information to the stack metadata.

**Comment by martyspiewak** [comment]
This should be possible to do for each package.

It seems like there is a CPE for all debian 10 as well (`cpe:2.3:o:debian:debian_linux:10.0:*:*:*:*:*:*:*`). I'm not sure if it would make sense to include that or not, but it seems like the package CPE would make sense to include with each package.

Here's [a CVE](https://nvd.nist.gov/vuln/detail/CVE-2021-25215) that has both the debian CPE, as well as the package CPE. [This CVE](https://nvd.nist.gov/vuln/detail/CVE-2019-25034), though, only has the package CPE on it.

One thing to note is that this will require looking up the correct CPE format for each dependency that is included in our stacks. Once we know the format we can automate changing the version number, but there is no way to automate the process of figuring out the CPE format.

For example, the CPE for `unbound` looks like: `cpe:2.3:a:nlnetlabs:unbound:0.7.1:*:*:*:*:*:*:*`, whereas the CPE for `clamav` looks like: `cpe:2.3:a:clamav:clamav:0.103.0:*:*:*:*:*:*:*`. 

We'd have to look up this format for each package on the stack images. This might introduce some complexity if we ever add a package because we will have to remember to not only add the CPE for that package, but also add CPEs for any dependencies of that package that will get installed with it.

**Comment by sophiewigmore** [comment]
Upon initial investigation using @martyspiewak's context we have discovered that there would be great amount of manual work needed in order to add the CPE formats for the hundreds of OS level packages we include in the stacks.  On top of that work, there are also some dependencies that are included in the stacks, that do not have associated CPE entries in the NIST database.

These challenges in conjunction with the fact that there already exist scanning tools that will reveal CVEs (such as [Trivy](https://github.com/aquasecurity/trivy)) have lead us to the decision not to pursue this investigation further at this time. We will reopen this issue if user need is surfaced that justifies the amount of effort needed for this initiative.
cc @ForestEckhardt
