### ISSUE TITLE
Run the "Build and Test Stack" workflow daily

### ISSUE THREAD

**Issue by ryanmoran** [paketo-buildpacks/stacks#75]
## Summary
The current automation for each of the stacks only runs when there is a matching USN or scheduled once a week:
* [Full](https://github.com/paketo-buildpacks/full-stack-release/blob/a86c7f93c6d6aa4e4a926d5a6b3081ca44c9b5a4/.github/workflows/build-and-test-stack.yml#L5-L7)
* [Base](https://github.com/paketo-buildpacks/base-stack-release/blob/89af7264a9423b0c47ab98bd77835cea0c519432/.github/workflows/build-and-test-stack.yml#L5-L7)
* [Tiny](https://github.com/paketo-buildpacks/tiny-stack-release/blob/6174998a82c44fe017780341cb9f0304ad2a1d07/.github/workflows/build-and-test-stack.yml#L5-L7)

Unfortunately, if the `ubuntu:bionic` base image is updated with CVE patches, but there isn't a trigger on a matching USN, the stack may not be rebuilt and published for up to a week.

I propose that we increase the scheduled frequency that this workflow runs to daily so that we are getting patches to the base image out within 24 hours.

**Comment by sophiewigmore** [comment]
I think the trigger did work, but because there wasn't a matching affected package in the repo, no commit was made. Here is why I think that:

The `build-and-test-stack` workflow that you're referring to runs weekly on Sunday as you said, but it's meant to pull in version bumps of dependencies that are not associated with any USN.

The same workflow also gets triggered by `check-usns`, which gets triggered by a USN coming in with an [`affected_package`](https://github.com/paketo-buildpacks/stack-usns/commit/8c25daeaef66118a27b486f6940624a739cadbe6#diff-86c29299225ab7613573257d12bb9fa2d54f4a221d1160ffa629e0c80d029a9aR22) inside the list of USNs in the[ stacks-usns](https://github.com/paketo-buildpacks/stack-usns) repository.

For the specific USN in https://github.com/paketo-buildpacks/full-stack-release/issues/83, it looks like that USN did trigger a dispatch to the stack releases:
1. [This workflow](https://github.com/paketo-buildpacks/stack-usns/actions/runs/963176019) in stack-usns triggered the release with that USN (see associated commit)
2. [This full-stack-release workflow](https://github.com/paketo-buildpacks/full-stack-release/runs/2891802608?check_suite_focus=true) was the workflow that got triggered. 

It looks like because there wasn't an exact matching package in the build or run receipts, no commit was made with the USN to the full stack USN file.

I feel like beyond making the cron job occur more often, we should figure out why our automation didn't consider the new USN relevant to the stack release. Maybe it would be good to make it more often since we aim to ship patches within 48 hours, but there might be a deeper problem with our automation.

Edit:
I do see the failed workflows that should've picked this up earlier: https://github.com/paketo-buildpacks/full-stack-release/actions/runs/953569123. However, I still am wondering why this USN wasn't picked up in the check-usn workflow.

**Comment by ryanmoran** [comment]
I think I'm having trouble seeing how the `linux-libc-dev` package was something that Trivy picked up as affected by the CVEs, but that Ubuntu didn't report it as affected in the USNs. The pages for neither of these CVEs show up for me:
* https://avd.aquasec.com/nvd/cve-2021-3600
* https://avd.aquasec.com/nvd/cve-2021-3609

Does this mean that these won't show up at some point in the future? I don't know. I just don't see how Trivy connected the dots between these CVEs and this package. Clearly the way we are doing it doesn't see that.

**Comment by sophiewigmore** [comment]
Exactly. Even when `linux-libc-dev:amd64` was added, no associated USN was added to the USNs list in the same commit (as I would expect for a dependency bump associated with a USN). 
But, how did the stack-usns workflow that found the USN of interest know to send a dispatch?

Where is this disconnect coming from?

**Comment by ryanmoran** [comment]
My understanding is that it always sends a dispatch. The `x-stack-release` repo then compares the affected packages list from each USN to the packages in the stack. So, the job runs, but does nothing because there are no matching packages.

**Comment by sophiewigmore** [comment]
Ah ok that clears that up then. I was under the impression the triggers only happened when there were matching affected packages.

**Comment by sophiewigmore** [comment]
I spent some more time looking into this.

Following [this issue on Trivy](https://github.com/aquasecurity/trivy/issues/105), it looks like they collect vulnerability information from many different sources in this repo: https://github.com/aquasecurity/vuln-list, whereas we just look at https://ubuntu.com/security/notices. The CVEs associated with USN-5003-1 can be found on NVD, Debian, Ubuntu, and Redhat's vulnerability files in that repo, which might be why they can connect the dots. I don't see any explicit mentions of the `linux-libc-dev` package though...

RE: why the associated CVE pages might have 404 statuses 

Within the [vuln-list Ubuntu entry](https://github.com/aquasecurity/vuln-list/blob/7698854a8e71c2631efca0151d8a2365f2cec586/ubuntu/2021/CVE-2021-3600.json) for CVE-2021-3600, the referenced [Mitre CVE page](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3600) says `** RESERVED ** This candidate has been reserved by an organization or individual that will use it when announcing a new security problem. When the candidate has been publicized, the details for this candidate will be provided.` I'll keep an eye out for any updates here, it might mean that the CVEs are being researched still so they removed entries for the time being.
