### ISSUE TITLE
How can i modify the default user group ?

### ISSUE THREAD

**Issue by laosiyao** [paketo-buildpacks/stacks#85]
## What happened?

I built a image use --builder paketobuildpacks/builder:base , but my app went wrong cause no permission.
```
> apt-get update
Reading package lists... Done
E: List directory /var/lib/apt/lists/partial is missing. - Acquire (13: Permission denied)

```
Then i found that the run image of paketobuildpacks stacks sets the default user:
```
ARG cnb_uid=1000
ARG cnb_gid=1000
RUN groupadd cnb --gid ${cnb_gid} && \
  useradd --uid ${cnb_uid} --gid ${cnb_gid} -m -s /bin/bash cnb
```
As i use k8s ,  I tried set   `runAsUser: 0` or `--allow-privileged=true` force  it to use root and it works, but this is not a good solution i thought.

How can i modify the default user group in pack build command?

## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.
pack 0.20.0+git-66a4f32.build-2668

* What buildpacks are you using? Please include versions.
paketobuildpacks/builder:base

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?

## Checklist

* [ ] I have included log output.
* [ ] The log output includes an error message.
* [ ] I have included steps for reproduction.

**Comment by sophiewigmore** [comment]
Hi there @laosiyao. You are correct, the user is set to non-root during build and run, and can only write to `/layers`, `/workspace`, `/home/<user>`, and `/tmp`. This is set as a part of the [Cloud Native Buildpack policy](https://github.com/buildpacks/spec/blob/main/platform.md#build-image) for secure container environments. The platform (pack) doesn't actually enforce this, which is why you were able to override the user group. It's not recommended

**Comment by sophiewigmore** [comment]
Hi there @laosiyao. You are correct, the user is set to non-root during build and run, and can only write to `/layers`, `/workspace`, `/home/<user>`, and `/tmp`. This is a rule set as a part of the [Cloud Native Buildpack policy](https://github.com/buildpacks/spec/blob/main/platform.md#build-image) for secure container environments. This policy is set for a reason, it's not recommended to override the user.

**Comment by sophiewigmore** [comment]
If you're interested in discussing this policy it might be helpful to chat with the folks in that project, the CNB Slack channel is at buildpacks.slack.com!

**Comment by sophiewigmore** [comment]
@laosiyao I am closing this issue due to a lack of activity. Please feel free to re-open it if you are still interested in this topic.

**Comment by andresflorezp** [comment]
Hello @sophiewigmore, I've worked in a POC in kubernetes with paketo,the issue is that the permissions we handle at company level and user_ui are 5000 not 1000, imagine more than 300 microservices where we have to change the guid one by one is too much, my question is have any environment variable to change the number of CNB_USER_ID and specify permissions to an extra folder could be in this case /opt

**Comment by sophiewigmore** [comment]
Hi @andresflorezp, right now, there is no quick fix to change the `CNB_USER_ID` because it is baked into the stack image we provide. 

An option could be to create a custom stack images with your specified user ID ([like we do here](https://github.com/paketo-buildpacks/stacks/blob/main/bionic/cnb/build/Dockerfile) and [here](https://github.com/paketo-buildpacks/stacks/blob/main/bionic/cnb/run/Dockerfile)), push the new stack image to a registry, and then modify the builder to use the custom stack (`pack create-builder` if you're using pack).

**Comment by 24601** [comment]
@sophiewigmore - thanks for the insights here, and we're in a similar situation as @andresflorezp: the UID is not really negotiable, and how knative works (and cloud native in general) is that setting UIDs are build time is an anti-pattern. So much so, that Openshift basically randomly assigns UIDs at runtime from a given range. Now, you can defeat this by making the range 1000-1000, but this then breaks tons of other things in the ecosystem that honor that practice/pattern (of not hard coding a UID at build time). 

Of course, we could take up maintenance of our own buildpack, but the whole value of "cloud-native" is that these such things are obviated by following such patterns/conventions. 

We'd be happy to contribute/work on a configurable solution, so I don't mean to come here to just complain, but I want to gauge if this is something the contributors/commiters of Paketo are convinced of/interested in before we go down this road...

Thoughts?

**Comment by robdimsdale** [comment]
@ekcasey do you have any thoughts on this? Is dynamic/run-time UIDs/GIDs something that is supported? The [spec](https://github.com/buildpacks/spec/blob/main/platform.md#build-image) doesn't really mention whether the images can be dynamic or not - simply that the UID for the run and build images should be different.
